sudo: required

language: python
python:
  - 3.5
  - 3.6
  
services:
  - docker

before_install:
  - docker pull postgres:9.6
  - docker run -p 127.0.0.1:7777:5432 -e POSTGRES_PASSWORD=password -d postgres:10
  - ./src/scripts/wait-for-pg.sh

install:
  - pip install cython && pip install -r src/requirements.txt

script:
  - cd src && pytest
