version: '2'
services:
  nycdb:
    image: aepyornis/nyc-db:0.0.1
    volumes:
      - ./:/opt/nyc-db
    depends_on:
      - pg
    environment:
      - NYCDB_DOCKER=true
  pg:
    image: postgres:9.6
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=nycdb
