---

nycdb_packages:
  - sudo
  - wget
  - curl
  - zip
  - unzip
  - bzip2
  - git
  - tmux
  - htop
  - build-essential
  - python3
  - python3-dev
  - python3-psycopg2
  - python3-venv
  - postgresql-client
  - postgresql
  - postgresql-contrib
  - libpq-dev
