---
- name: Install Required packages
  apt:
    update_cache: yes
    name: "{{ item }}"
  with_items: "{{ nycdb_packages }}"
  notify:
    - restart postgresql

    
- name: Installling csvkt
  pip:
    executable: /usr/bin/pip2
    name: csvkit


- name: Setup postgres db
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_db:
      name: "{{ nycdb_database_name }}"


- name: Adding extension pg_trgm to db
  become_method: sudo
  become_user: postgres
  postgresql_ext:
    name: pg_trgm
    db: "{{ nycdb_database_name }}"

      
- name: Create database user
  become_method: sudo
  become_user: postgres
  postgresql_user: 
    db: "{{ nycdb_database_name}}"
    name: "{{ nycdb_database_user }}" 
    password: "{{ nycdb_database_password }}"
    encrypted: yes
    priv: ALL

    
- name: Ensure database user does not have unnecessary privileges
  become_method: sudo
  become_user: postgres
  postgresql_user:
    name: "{{ nycdb_database_user }}" 
    role_attr_flags: NOSUPERUSER,NOCREATEDB

    
- name: Create /srv/nyc-db
  file:
    path: /srv/nyc-db
    state: directory
    owner: ubuntu

    
- name: Clone the nyc-db repo
  become: yes
  become_user: ubuntu
  git:
    repo: https://github.com/aepyornis/nyc-db.git
    dest: /srv/nyc-db
    recursive: yes
    
- name: Installing Gems for 311 module
  become: yes
  become_user: ubuntu
  bundler:
    state: present
    executable: ~/.rvm/gems/ruby-2.4.0/bin/bundler
    gemfile: /srv/nyc-db/modules/311/Gemfile
    

- name: Setup env.sh
  become: yes
  become_user: ubuntu
  template:
    src: "env.sh.j2"
    dest: "/srv/nyc-db/env.sh"
