---
- name: Install Required packages
  apt:
    update_cache: yes
    name: "{{ item }}"
  with_items: "{{ nycdb_packages }}"
  notify:
    - restart postgresql

- name: Setup postgres db
  become: yes
  become_user: postgres
  postgresql_db:
      name: "{{ nycdb_database_name }}"
      
- name: Create database user
  become: yes
  become_user: postgres
  postgresql_user: 
    db: "{{ nycdb_database_name}}"
    name: "{{ nycdb_database_user }}" 
    password: "{{ nycdb_database_password }}"
    encrypted: yes
    priv: ALL

    
- name: Ensure database user does not have unnecessary privileges
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ nycdb_database_user }}" 
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    
- name: Create /srv/nyc-db
  file:
    path: /srv/nyc-db
    state: directory
    owner: "{{ nycdb_user }}"
    
- name: Clone the nyc-db repo
  become: yes
  become_user: "{{ nycdb_user }}"
  git:
    repo: https://github.com/aepyornis/nyc-db.git
    dest: /srv/nyc-db
    version: master
