---
- name: Setup NYC-DB
  hosts: nycdb
  become: yes
  become_method: sudo

  roles:
    - common
    - { role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.4.0'],
        rvm1_user: 'ubuntu'
      }
