name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v3 

    - name: Start containers
      run: docker-compose build
    
    - name: Run tests
      run: docker-compose run --entrypoint="pytest tests" nycdb
